# Generated by Django 5.2.7 on 2025-10-23 11:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='ユーザネーム')),
                ('profile_comment', models.TextField(blank=True, verbose_name='プロフィールコメント')),
                ('gender', models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性'), ('other', 'その他')], max_length=10, verbose_name='性別')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='誕生年')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('political_party', models.CharField(blank=True, choices=[('none', '支持政党なし'), ('liberal', '自由民主党'), ('ishin', '維新の会'), ('kyosan', '共産党'), ('rikken', '立憲民主党'), ('kokumin', '国民民主党'), ('other', 'その他の党')], max_length=20, verbose_name='支持政党')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
