# Generated by Django 5.2.7 on 2025-10-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='生まれた年'),
        ),
    ]
