# Generated by Django 5.2.7 on 2025-11-02 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_userprofile_birth_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.userprofile'),
        ),
    ]
